package com.tokogame.dao;

import com.tokogame.domain.Belanja;
import com.tokogame.domain.BelanjaExample;
import java.util.List;

public interface BelanjaDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table belanja
     *
     * @ibatorgenerated Wed May 01 01:04:10 ICT 2013
     */
    int countByExample(BelanjaExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table belanja
     *
     * @ibatorgenerated Wed May 01 01:04:10 ICT 2013
     */
    int deleteByExample(BelanjaExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table belanja
     *
     * @ibatorgenerated Wed May 01 01:04:10 ICT 2013
     */
    int deleteByPrimaryKey(Integer pkBelanja);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table belanja
     *
     * @ibatorgenerated Wed May 01 01:04:10 ICT 2013
     */
    void insert(Belanja record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table belanja
     *
     * @ibatorgenerated Wed May 01 01:04:10 ICT 2013
     */
    void insertSelective(Belanja record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table belanja
     *
     * @ibatorgenerated Wed May 01 01:04:10 ICT 2013
     */
    List<Belanja> selectByExample(BelanjaExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table belanja
     *
     * @ibatorgenerated Wed May 01 01:04:10 ICT 2013
     */
    Belanja selectByPrimaryKey(Integer pkBelanja);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table belanja
     *
     * @ibatorgenerated Wed May 01 01:04:10 ICT 2013
     */
    int updateByExampleSelective(Belanja record, BelanjaExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table belanja
     *
     * @ibatorgenerated Wed May 01 01:04:10 ICT 2013
     */
    int updateByExample(Belanja record, BelanjaExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table belanja
     *
     * @ibatorgenerated Wed May 01 01:04:10 ICT 2013
     */
    int updateByPrimaryKeySelective(Belanja record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table belanja
     *
     * @ibatorgenerated Wed May 01 01:04:10 ICT 2013
     */
    int updateByPrimaryKey(Belanja record);
}