package com.tokogame.dao;

import com.tokogame.domain.Belanja;
import com.tokogame.domain.BelanjaExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class BelanjaDAOImpl extends SqlMapClientDaoSupport implements BelanjaDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table belanja
     *
     * @ibatorgenerated Mon May 06 23:07:04 ICT 2013
     */
    public BelanjaDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table belanja
     *
     * @ibatorgenerated Mon May 06 23:07:04 ICT 2013
     */
    public int countByExample(BelanjaExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("belanja.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table belanja
     *
     * @ibatorgenerated Mon May 06 23:07:04 ICT 2013
     */
    public int deleteByExample(BelanjaExample example) {
        int rows = getSqlMapClientTemplate().delete("belanja.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table belanja
     *
     * @ibatorgenerated Mon May 06 23:07:04 ICT 2013
     */
    public int deleteByPrimaryKey(Integer pkBelanja) {
        Belanja key = new Belanja();
        key.setPkBelanja(pkBelanja);
        int rows = getSqlMapClientTemplate().delete("belanja.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table belanja
     *
     * @ibatorgenerated Mon May 06 23:07:04 ICT 2013
     */
    public void insert(Belanja record) {
        getSqlMapClientTemplate().insert("belanja.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table belanja
     *
     * @ibatorgenerated Mon May 06 23:07:04 ICT 2013
     */
    public void insertSelective(Belanja record) {
        getSqlMapClientTemplate().insert("belanja.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table belanja
     *
     * @ibatorgenerated Mon May 06 23:07:04 ICT 2013
     */
    @SuppressWarnings("unchecked")
    public List<Belanja> selectByExample(BelanjaExample example) {
        List<Belanja> list = getSqlMapClientTemplate().queryForList("belanja.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table belanja
     *
     * @ibatorgenerated Mon May 06 23:07:04 ICT 2013
     */
    public Belanja selectByPrimaryKey(Integer pkBelanja) {
        Belanja key = new Belanja();
        key.setPkBelanja(pkBelanja);
        Belanja record = (Belanja) getSqlMapClientTemplate().queryForObject("belanja.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table belanja
     *
     * @ibatorgenerated Mon May 06 23:07:04 ICT 2013
     */
    public int updateByExampleSelective(Belanja record, BelanjaExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("belanja.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table belanja
     *
     * @ibatorgenerated Mon May 06 23:07:04 ICT 2013
     */
    public int updateByExample(Belanja record, BelanjaExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("belanja.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table belanja
     *
     * @ibatorgenerated Mon May 06 23:07:04 ICT 2013
     */
    public int updateByPrimaryKeySelective(Belanja record) {
        int rows = getSqlMapClientTemplate().update("belanja.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table belanja
     *
     * @ibatorgenerated Mon May 06 23:07:04 ICT 2013
     */
    public int updateByPrimaryKey(Belanja record) {
        int rows = getSqlMapClientTemplate().update("belanja.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table belanja
     *
     * @ibatorgenerated Mon May 06 23:07:04 ICT 2013
     */
    private static class UpdateByExampleParms extends BelanjaExample {
        private Object record;

        public UpdateByExampleParms(Object record, BelanjaExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}