package com.tokogame.dao;

import com.tokogame.domain.Item;
import com.tokogame.domain.ItemExample;
import java.util.List;

public interface ItemDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item
     *
     * @ibatorgenerated Sat May 04 10:30:42 ICT 2013
     */
    int countByExample(ItemExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item
     *
     * @ibatorgenerated Sat May 04 10:30:42 ICT 2013
     */
    int deleteByExample(ItemExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item
     *
     * @ibatorgenerated Sat May 04 10:30:42 ICT 2013
     */
    int deleteByPrimaryKey(Integer pkItem);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item
     *
     * @ibatorgenerated Sat May 04 10:30:42 ICT 2013
     */
    void insert(Item record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item
     *
     * @ibatorgenerated Sat May 04 10:30:42 ICT 2013
     */
    void insertSelective(Item record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item
     *
     * @ibatorgenerated Sat May 04 10:30:42 ICT 2013
     */
    List<Item> selectByExample(ItemExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item
     *
     * @ibatorgenerated Sat May 04 10:30:42 ICT 2013
     */
    Item selectByPrimaryKey(Integer pkItem);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item
     *
     * @ibatorgenerated Sat May 04 10:30:42 ICT 2013
     */
    int updateByExampleSelective(Item record, ItemExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item
     *
     * @ibatorgenerated Sat May 04 10:30:42 ICT 2013
     */
    int updateByExample(Item record, ItemExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item
     *
     * @ibatorgenerated Sat May 04 10:30:42 ICT 2013
     */
    int updateByPrimaryKeySelective(Item record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item
     *
     * @ibatorgenerated Sat May 04 10:30:42 ICT 2013
     */
    int updateByPrimaryKey(Item record);
}