package com.tokogame.dao;

import com.tokogame.domain.Item;
import com.tokogame.domain.ItemExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ItemDAOImpl extends SqlMapClientDaoSupport implements ItemDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public ItemDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public int countByExample(ItemExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("item.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public int deleteByExample(ItemExample example) {
        int rows = getSqlMapClientTemplate().delete("item.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public int deleteByPrimaryKey(Integer pkItem) {
        Item key = new Item();
        key.setPkItem(pkItem);
        int rows = getSqlMapClientTemplate().delete("item.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public void insert(Item record) {
        getSqlMapClientTemplate().insert("item.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public void insertSelective(Item record) {
        getSqlMapClientTemplate().insert("item.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    @SuppressWarnings("unchecked")
    public List<Item> selectByExample(ItemExample example) {
        List<Item> list = getSqlMapClientTemplate().queryForList("item.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public Item selectByPrimaryKey(Integer pkItem) {
        Item key = new Item();
        key.setPkItem(pkItem);
        Item record = (Item) getSqlMapClientTemplate().queryForObject("item.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public int updateByExampleSelective(Item record, ItemExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("item.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public int updateByExample(Item record, ItemExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("item.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public int updateByPrimaryKeySelective(Item record) {
        int rows = getSqlMapClientTemplate().update("item.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public int updateByPrimaryKey(Item record) {
        int rows = getSqlMapClientTemplate().update("item.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table item
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    private static class UpdateByExampleParms extends ItemExample {
        private Object record;

        public UpdateByExampleParms(Object record, ItemExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}