package com.tokogame.dao;

import com.tokogame.domain.Kategori;
import com.tokogame.domain.KategoriExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class KategoriDAOImpl extends SqlMapClientDaoSupport implements KategoriDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kategori
     *
     * @ibatorgenerated Fri May 10 02:42:01 ICT 2013
     */
    public KategoriDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kategori
     *
     * @ibatorgenerated Fri May 10 02:42:01 ICT 2013
     */
    public int countByExample(KategoriExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("kategori.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kategori
     *
     * @ibatorgenerated Fri May 10 02:42:01 ICT 2013
     */
    public int deleteByExample(KategoriExample example) {
        int rows = getSqlMapClientTemplate().delete("kategori.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kategori
     *
     * @ibatorgenerated Fri May 10 02:42:01 ICT 2013
     */
    public int deleteByPrimaryKey(Integer pkKategori) {
        Kategori key = new Kategori();
        key.setPkKategori(pkKategori);
        int rows = getSqlMapClientTemplate().delete("kategori.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kategori
     *
     * @ibatorgenerated Fri May 10 02:42:01 ICT 2013
     */
    public void insert(Kategori record) {
        getSqlMapClientTemplate().insert("kategori.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kategori
     *
     * @ibatorgenerated Fri May 10 02:42:01 ICT 2013
     */
    public void insertSelective(Kategori record) {
        getSqlMapClientTemplate().insert("kategori.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kategori
     *
     * @ibatorgenerated Fri May 10 02:42:01 ICT 2013
     */
    @SuppressWarnings("unchecked")
    public List<Kategori> selectByExample(KategoriExample example) {
        List<Kategori> list = getSqlMapClientTemplate().queryForList("kategori.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kategori
     *
     * @ibatorgenerated Fri May 10 02:42:01 ICT 2013
     */
    public Kategori selectByPrimaryKey(Integer pkKategori) {
        Kategori key = new Kategori();
        key.setPkKategori(pkKategori);
        Kategori record = (Kategori) getSqlMapClientTemplate().queryForObject("kategori.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kategori
     *
     * @ibatorgenerated Fri May 10 02:42:01 ICT 2013
     */
    public int updateByExampleSelective(Kategori record, KategoriExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("kategori.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kategori
     *
     * @ibatorgenerated Fri May 10 02:42:01 ICT 2013
     */
    public int updateByExample(Kategori record, KategoriExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("kategori.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kategori
     *
     * @ibatorgenerated Fri May 10 02:42:01 ICT 2013
     */
    public int updateByPrimaryKeySelective(Kategori record) {
        int rows = getSqlMapClientTemplate().update("kategori.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kategori
     *
     * @ibatorgenerated Fri May 10 02:42:01 ICT 2013
     */
    public int updateByPrimaryKey(Kategori record) {
        int rows = getSqlMapClientTemplate().update("kategori.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table kategori
     *
     * @ibatorgenerated Fri May 10 02:42:01 ICT 2013
     */
    private static class UpdateByExampleParms extends KategoriExample {
        private Object record;

        public UpdateByExampleParms(Object record, KategoriExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}