package com.tokogame.dao;

import com.tokogame.domain.Kategori;
import com.tokogame.domain.KategoriExample;
import java.util.List;

public interface KategoriDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kategori
     *
     * @ibatorgenerated Fri May 10 02:42:01 ICT 2013
     */
    int countByExample(KategoriExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kategori
     *
     * @ibatorgenerated Fri May 10 02:42:01 ICT 2013
     */
    int deleteByExample(KategoriExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kategori
     *
     * @ibatorgenerated Fri May 10 02:42:01 ICT 2013
     */
    int deleteByPrimaryKey(Integer pkKategori);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kategori
     *
     * @ibatorgenerated Fri May 10 02:42:01 ICT 2013
     */
    void insert(Kategori record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kategori
     *
     * @ibatorgenerated Fri May 10 02:42:01 ICT 2013
     */
    void insertSelective(Kategori record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kategori
     *
     * @ibatorgenerated Fri May 10 02:42:01 ICT 2013
     */
    List<Kategori> selectByExample(KategoriExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kategori
     *
     * @ibatorgenerated Fri May 10 02:42:01 ICT 2013
     */
    Kategori selectByPrimaryKey(Integer pkKategori);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kategori
     *
     * @ibatorgenerated Fri May 10 02:42:01 ICT 2013
     */
    int updateByExampleSelective(Kategori record, KategoriExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kategori
     *
     * @ibatorgenerated Fri May 10 02:42:01 ICT 2013
     */
    int updateByExample(Kategori record, KategoriExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kategori
     *
     * @ibatorgenerated Fri May 10 02:42:01 ICT 2013
     */
    int updateByPrimaryKeySelective(Kategori record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kategori
     *
     * @ibatorgenerated Fri May 10 02:42:01 ICT 2013
     */
    int updateByPrimaryKey(Kategori record);
}