package com.tokogame.dao;

import com.tokogame.domain.Koleksi;
import com.tokogame.domain.KoleksiExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class KoleksiDAOImpl extends SqlMapClientDaoSupport implements KoleksiDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi
     *
     * @ibatorgenerated Tue Apr 16 12:50:12 ICT 2013
     */
    public KoleksiDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi
     *
     * @ibatorgenerated Tue Apr 16 12:50:12 ICT 2013
     */
    public int countByExample(KoleksiExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("koleksi.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi
     *
     * @ibatorgenerated Tue Apr 16 12:50:12 ICT 2013
     */
    public int deleteByExample(KoleksiExample example) {
        int rows = getSqlMapClientTemplate().delete("koleksi.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi
     *
     * @ibatorgenerated Tue Apr 16 12:50:12 ICT 2013
     */
    public int deleteByPrimaryKey(Integer koleksiId) {
        Koleksi key = new Koleksi();
        key.setKoleksiId(koleksiId);
        int rows = getSqlMapClientTemplate().delete("koleksi.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi
     *
     * @ibatorgenerated Tue Apr 16 12:50:12 ICT 2013
     */
    public void insert(Koleksi record) {
        getSqlMapClientTemplate().insert("koleksi.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi
     *
     * @ibatorgenerated Tue Apr 16 12:50:12 ICT 2013
     */
    public void insertSelective(Koleksi record) {
        getSqlMapClientTemplate().insert("koleksi.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi
     *
     * @ibatorgenerated Tue Apr 16 12:50:12 ICT 2013
     */
    @SuppressWarnings("unchecked")
    public List<Koleksi> selectByExample(KoleksiExample example) {
        List<Koleksi> list = getSqlMapClientTemplate().queryForList("koleksi.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi
     *
     * @ibatorgenerated Tue Apr 16 12:50:12 ICT 2013
     */
    public Koleksi selectByPrimaryKey(Integer koleksiId) {
        Koleksi key = new Koleksi();
        key.setKoleksiId(koleksiId);
        Koleksi record = (Koleksi) getSqlMapClientTemplate().queryForObject("koleksi.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi
     *
     * @ibatorgenerated Tue Apr 16 12:50:12 ICT 2013
     */
    public int updateByExampleSelective(Koleksi record, KoleksiExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("koleksi.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi
     *
     * @ibatorgenerated Tue Apr 16 12:50:12 ICT 2013
     */
    public int updateByExample(Koleksi record, KoleksiExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("koleksi.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi
     *
     * @ibatorgenerated Tue Apr 16 12:50:12 ICT 2013
     */
    public int updateByPrimaryKeySelective(Koleksi record) {
        int rows = getSqlMapClientTemplate().update("koleksi.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi
     *
     * @ibatorgenerated Tue Apr 16 12:50:12 ICT 2013
     */
    public int updateByPrimaryKey(Koleksi record) {
        int rows = getSqlMapClientTemplate().update("koleksi.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table koleksi
     *
     * @ibatorgenerated Tue Apr 16 12:50:12 ICT 2013
     */
    private static class UpdateByExampleParms extends KoleksiExample {
        private Object record;

        public UpdateByExampleParms(Object record, KoleksiExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}