package com.tokogame.dao;

import com.tokogame.domain.Koleksi;
import com.tokogame.domain.KoleksiExample;
import java.util.List;

public interface KoleksiDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    int countByExample(KoleksiExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    int deleteByExample(KoleksiExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    int deleteByPrimaryKey(Integer pkKoleksi);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    void insert(Koleksi record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    void insertSelective(Koleksi record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    List<Koleksi> selectByExample(KoleksiExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    Koleksi selectByPrimaryKey(Integer pkKoleksi);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    int updateByExampleSelective(Koleksi record, KoleksiExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    int updateByExample(Koleksi record, KoleksiExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    int updateByPrimaryKeySelective(Koleksi record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    int updateByPrimaryKey(Koleksi record);
}