package com.tokogame.dao;

import com.tokogame.domain.KoleksiRelation;
import com.tokogame.domain.KoleksiRelationExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class KoleksiRelationDAOImpl extends SqlMapClientDaoSupport implements KoleksiRelationDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi_relation
     *
     * @ibatorgenerated Tue May 14 23:15:06 ICT 2013
     */
    public KoleksiRelationDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi_relation
     *
     * @ibatorgenerated Tue May 14 23:15:06 ICT 2013
     */
    public int countByExample(KoleksiRelationExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("koleksi_relation.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi_relation
     *
     * @ibatorgenerated Tue May 14 23:15:06 ICT 2013
     */
    public int deleteByExample(KoleksiRelationExample example) {
        int rows = getSqlMapClientTemplate().delete("koleksi_relation.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi_relation
     *
     * @ibatorgenerated Tue May 14 23:15:06 ICT 2013
     */
    public int deleteByPrimaryKey(Integer pkKoleksiRelation) {
        KoleksiRelation key = new KoleksiRelation();
        key.setPkKoleksiRelation(pkKoleksiRelation);
        int rows = getSqlMapClientTemplate().delete("koleksi_relation.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi_relation
     *
     * @ibatorgenerated Tue May 14 23:15:06 ICT 2013
     */
    public void insert(KoleksiRelation record) {
        getSqlMapClientTemplate().insert("koleksi_relation.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi_relation
     *
     * @ibatorgenerated Tue May 14 23:15:06 ICT 2013
     */
    public void insertSelective(KoleksiRelation record) {
        getSqlMapClientTemplate().insert("koleksi_relation.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi_relation
     *
     * @ibatorgenerated Tue May 14 23:15:06 ICT 2013
     */
    @SuppressWarnings("unchecked")
    public List<KoleksiRelation> selectByExample(KoleksiRelationExample example) {
        List<KoleksiRelation> list = getSqlMapClientTemplate().queryForList("koleksi_relation.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi_relation
     *
     * @ibatorgenerated Tue May 14 23:15:06 ICT 2013
     */
    public KoleksiRelation selectByPrimaryKey(Integer pkKoleksiRelation) {
        KoleksiRelation key = new KoleksiRelation();
        key.setPkKoleksiRelation(pkKoleksiRelation);
        KoleksiRelation record = (KoleksiRelation) getSqlMapClientTemplate().queryForObject("koleksi_relation.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi_relation
     *
     * @ibatorgenerated Tue May 14 23:15:06 ICT 2013
     */
    public int updateByExampleSelective(KoleksiRelation record, KoleksiRelationExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("koleksi_relation.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi_relation
     *
     * @ibatorgenerated Tue May 14 23:15:06 ICT 2013
     */
    public int updateByExample(KoleksiRelation record, KoleksiRelationExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("koleksi_relation.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi_relation
     *
     * @ibatorgenerated Tue May 14 23:15:06 ICT 2013
     */
    public int updateByPrimaryKeySelective(KoleksiRelation record) {
        int rows = getSqlMapClientTemplate().update("koleksi_relation.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table koleksi_relation
     *
     * @ibatorgenerated Tue May 14 23:15:06 ICT 2013
     */
    public int updateByPrimaryKey(KoleksiRelation record) {
        int rows = getSqlMapClientTemplate().update("koleksi_relation.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table koleksi_relation
     *
     * @ibatorgenerated Tue May 14 23:15:06 ICT 2013
     */
    private static class UpdateByExampleParms extends KoleksiRelationExample {
        private Object record;

        public UpdateByExampleParms(Object record, KoleksiRelationExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}