package com.tokogame.dao;

import com.tokogame.domain.Konfigurasi;
import com.tokogame.domain.KonfigurasiExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class KonfigurasiDAOImpl extends SqlMapClientDaoSupport implements KonfigurasiDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table konfigurasi
     *
     * @ibatorgenerated Sat May 11 00:38:31 ICT 2013
     */
    public KonfigurasiDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table konfigurasi
     *
     * @ibatorgenerated Sat May 11 00:38:31 ICT 2013
     */
    public int countByExample(KonfigurasiExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("konfigurasi.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table konfigurasi
     *
     * @ibatorgenerated Sat May 11 00:38:31 ICT 2013
     */
    public int deleteByExample(KonfigurasiExample example) {
        int rows = getSqlMapClientTemplate().delete("konfigurasi.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table konfigurasi
     *
     * @ibatorgenerated Sat May 11 00:38:31 ICT 2013
     */
    public int deleteByPrimaryKey(Integer pkKonfigurasi) {
        Konfigurasi key = new Konfigurasi();
        key.setPkKonfigurasi(pkKonfigurasi);
        int rows = getSqlMapClientTemplate().delete("konfigurasi.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table konfigurasi
     *
     * @ibatorgenerated Sat May 11 00:38:31 ICT 2013
     */
    public void insert(Konfigurasi record) {
        getSqlMapClientTemplate().insert("konfigurasi.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table konfigurasi
     *
     * @ibatorgenerated Sat May 11 00:38:31 ICT 2013
     */
    public void insertSelective(Konfigurasi record) {
        getSqlMapClientTemplate().insert("konfigurasi.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table konfigurasi
     *
     * @ibatorgenerated Sat May 11 00:38:31 ICT 2013
     */
    @SuppressWarnings("unchecked")
    public List<Konfigurasi> selectByExample(KonfigurasiExample example) {
        List<Konfigurasi> list = getSqlMapClientTemplate().queryForList("konfigurasi.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table konfigurasi
     *
     * @ibatorgenerated Sat May 11 00:38:31 ICT 2013
     */
    public Konfigurasi selectByPrimaryKey(Integer pkKonfigurasi) {
        Konfigurasi key = new Konfigurasi();
        key.setPkKonfigurasi(pkKonfigurasi);
        Konfigurasi record = (Konfigurasi) getSqlMapClientTemplate().queryForObject("konfigurasi.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table konfigurasi
     *
     * @ibatorgenerated Sat May 11 00:38:31 ICT 2013
     */
    public int updateByExampleSelective(Konfigurasi record, KonfigurasiExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("konfigurasi.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table konfigurasi
     *
     * @ibatorgenerated Sat May 11 00:38:31 ICT 2013
     */
    public int updateByExample(Konfigurasi record, KonfigurasiExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("konfigurasi.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table konfigurasi
     *
     * @ibatorgenerated Sat May 11 00:38:31 ICT 2013
     */
    public int updateByPrimaryKeySelective(Konfigurasi record) {
        int rows = getSqlMapClientTemplate().update("konfigurasi.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table konfigurasi
     *
     * @ibatorgenerated Sat May 11 00:38:31 ICT 2013
     */
    public int updateByPrimaryKey(Konfigurasi record) {
        int rows = getSqlMapClientTemplate().update("konfigurasi.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table konfigurasi
     *
     * @ibatorgenerated Sat May 11 00:38:31 ICT 2013
     */
    private static class UpdateByExampleParms extends KonfigurasiExample {
        private Object record;

        public UpdateByExampleParms(Object record, KonfigurasiExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}