package com.tokogame.dao;

import com.tokogame.domain.Opname;
import com.tokogame.domain.OpnameExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class OpnameDAOImpl extends SqlMapClientDaoSupport implements OpnameDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table opname
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    public OpnameDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table opname
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    public int countByExample(OpnameExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("opname.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table opname
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    public int deleteByExample(OpnameExample example) {
        int rows = getSqlMapClientTemplate().delete("opname.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table opname
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    public int deleteByPrimaryKey(Integer pkOpname) {
        Opname key = new Opname();
        key.setPkOpname(pkOpname);
        int rows = getSqlMapClientTemplate().delete("opname.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table opname
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    public void insert(Opname record) {
        getSqlMapClientTemplate().insert("opname.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table opname
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    public void insertSelective(Opname record) {
        getSqlMapClientTemplate().insert("opname.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table opname
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    @SuppressWarnings("unchecked")
    public List<Opname> selectByExample(OpnameExample example) {
        List<Opname> list = getSqlMapClientTemplate().queryForList("opname.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table opname
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    public Opname selectByPrimaryKey(Integer pkOpname) {
        Opname key = new Opname();
        key.setPkOpname(pkOpname);
        Opname record = (Opname) getSqlMapClientTemplate().queryForObject("opname.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table opname
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    public int updateByExampleSelective(Opname record, OpnameExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("opname.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table opname
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    public int updateByExample(Opname record, OpnameExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("opname.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table opname
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    public int updateByPrimaryKeySelective(Opname record) {
        int rows = getSqlMapClientTemplate().update("opname.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table opname
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    public int updateByPrimaryKey(Opname record) {
        int rows = getSqlMapClientTemplate().update("opname.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table opname
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    private static class UpdateByExampleParms extends OpnameExample {
        private Object record;

        public UpdateByExampleParms(Object record, OpnameExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}