package com.tokogame.dao;

import com.tokogame.domain.Opname;
import com.tokogame.domain.OpnameExample;
import java.util.List;

public interface OpnameDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table opname
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    int countByExample(OpnameExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table opname
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    int deleteByExample(OpnameExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table opname
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    int deleteByPrimaryKey(Integer pkOpname);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table opname
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    void insert(Opname record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table opname
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    void insertSelective(Opname record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table opname
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    List<Opname> selectByExample(OpnameExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table opname
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    Opname selectByPrimaryKey(Integer pkOpname);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table opname
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    int updateByExampleSelective(Opname record, OpnameExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table opname
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    int updateByExample(Opname record, OpnameExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table opname
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    int updateByPrimaryKeySelective(Opname record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table opname
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    int updateByPrimaryKey(Opname record);
}