package com.tokogame.dao;

import com.tokogame.domain.PembelianDetail;
import com.tokogame.domain.PembelianDetailExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class PembelianDetailDAOImpl extends SqlMapClientDaoSupport implements PembelianDetailDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    public PembelianDetailDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    public int countByExample(PembelianDetailExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pembelian_detail.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    public int deleteByExample(PembelianDetailExample example) {
        int rows = getSqlMapClientTemplate().delete("pembelian_detail.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    public int deleteByPrimaryKey(Integer pkPembelianDetail) {
        PembelianDetail key = new PembelianDetail();
        key.setPkPembelianDetail(pkPembelianDetail);
        int rows = getSqlMapClientTemplate().delete("pembelian_detail.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    public void insert(PembelianDetail record) {
        getSqlMapClientTemplate().insert("pembelian_detail.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    public void insertSelective(PembelianDetail record) {
        getSqlMapClientTemplate().insert("pembelian_detail.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    @SuppressWarnings("unchecked")
    public List<PembelianDetail> selectByExample(PembelianDetailExample example) {
        List<PembelianDetail> list = getSqlMapClientTemplate().queryForList("pembelian_detail.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    public PembelianDetail selectByPrimaryKey(Integer pkPembelianDetail) {
        PembelianDetail key = new PembelianDetail();
        key.setPkPembelianDetail(pkPembelianDetail);
        PembelianDetail record = (PembelianDetail) getSqlMapClientTemplate().queryForObject("pembelian_detail.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    public int updateByExampleSelective(PembelianDetail record, PembelianDetailExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pembelian_detail.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    public int updateByExample(PembelianDetail record, PembelianDetailExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pembelian_detail.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    public int updateByPrimaryKeySelective(PembelianDetail record) {
        int rows = getSqlMapClientTemplate().update("pembelian_detail.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    public int updateByPrimaryKey(PembelianDetail record) {
        int rows = getSqlMapClientTemplate().update("pembelian_detail.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    private static class UpdateByExampleParms extends PembelianDetailExample {
        private Object record;

        public UpdateByExampleParms(Object record, PembelianDetailExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}