package com.tokogame.dao;

import com.tokogame.domain.PembelianDetail;
import com.tokogame.domain.PembelianDetailExample;
import java.util.List;

public interface PembelianDetailDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    int countByExample(PembelianDetailExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    int deleteByExample(PembelianDetailExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    int deleteByPrimaryKey(Integer pkPembelianDetail);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    void insert(PembelianDetail record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    void insertSelective(PembelianDetail record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    List<PembelianDetail> selectByExample(PembelianDetailExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    PembelianDetail selectByPrimaryKey(Integer pkPembelianDetail);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    int updateByExampleSelective(PembelianDetail record, PembelianDetailExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    int updateByExample(PembelianDetail record, PembelianDetailExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    int updateByPrimaryKeySelective(PembelianDetail record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    int updateByPrimaryKey(PembelianDetail record);
}