/**
 * 
 */
package com.tokogame.dao;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;

import org.springframework.orm.ibatis.SqlMapClientCallback;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.ibatis.sqlmap.client.SqlMapExecutor;
import com.tokogame.domain.Item;
import com.tokogame.domain.ItemExample;
import com.tokogame.domain.PembelianDetail;

/**
 * @author mardy jonathan
 *
 */
public class PembelianHelperDAOImpl extends SqlMapClientDaoSupport implements PembelianHelperDAO{

	/**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table item
     *
     * @ibatorgenerated Thu May 09 00:35:39 ICT 2013
     */
    private static class UpdateByExampleParms extends ItemExample {
        private Object record;

        public UpdateByExampleParms(Object record, ItemExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
	
	@Override
	public void insertListPembelianDetail(List<PembelianDetail> listPembelianDetail) {
		// TODO Auto-generated method stub
		getSqlMapClientTemplate().insert("pembelian_helper.insertListPembelian", listPembelianDetail);
	}
	
	@Override
	public List<HashMap> getListPembelian(HashMap<String, Object> map) {
		// TODO Auto-generated method stub
		List<HashMap> list = getSqlMapClientTemplate().queryForList("pembelian_helper.selectPembelian", map);
        return list;
	}

	@Override
	public void batchBelanjaDetail(final List<PembelianDetail> listPembelianDetail,final String process) {
		// TODO Auto-generated method stub
		getSqlMapClientTemplate().execute(new SqlMapClientCallback<Object>() {

			@Override
			public Object doInSqlMapClient(SqlMapExecutor executor) throws SQLException {
				// TODO Auto-generated method stub
				HashMap<String, Object> map = new HashMap<String, Object>();
				map.put("fkPembelian", listPembelianDetail.get(0).getFkPembelian());
				executor.startBatch();
				executor.update("pembelian_helper.updateMinusQtyItem", map);
				executor.delete("pembelian_helper.deleteDetailByFkPembelian", map);
				if(!"delete".equals(process)){
					executor.insert("pembelian_helper.insertListPembelian", listPembelianDetail);
					executor.update("pembelian_helper.updatePlusQtyItem", map);
				}
				return new Integer(executor.executeBatch());
			}
			
		});
	}

	@Override
	public void updateMinusQtyItem(HashMap<String, Object> map) {
		// TODO Auto-generated method stub
		getSqlMapClientTemplate().update("pembelian_helper.updateMinusQtyItem", map);
	}

	@Override
	public void updatePlusQtyItem(HashMap<String, Object> map) {
		// TODO Auto-generated method stub
		getSqlMapClientTemplate().update("pembelian_helper.updatePlusQtyItem", map);
	}

	@Override
	public void deleteDetailPembelian(HashMap<String, Object> map) {
		// TODO Auto-generated method stub
		getSqlMapClientTemplate().delete("pembelian_helper.deleteDetailByFkPembelian", map);
	}

}
