package com.tokogame.dao;

import com.tokogame.domain.Penjualan;
import com.tokogame.domain.PenjualanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class PenjualanDAOImpl extends SqlMapClientDaoSupport implements PenjualanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table penjualan
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    public PenjualanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table penjualan
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    public int countByExample(PenjualanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("penjualan.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table penjualan
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    public int deleteByExample(PenjualanExample example) {
        int rows = getSqlMapClientTemplate().delete("penjualan.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table penjualan
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    public int deleteByPrimaryKey(Integer pkPenjualan) {
        Penjualan key = new Penjualan();
        key.setPkPenjualan(pkPenjualan);
        int rows = getSqlMapClientTemplate().delete("penjualan.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table penjualan
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    public void insert(Penjualan record) {
        getSqlMapClientTemplate().insert("penjualan.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table penjualan
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    public void insertSelective(Penjualan record) {
        getSqlMapClientTemplate().insert("penjualan.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table penjualan
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    @SuppressWarnings("unchecked")
    public List<Penjualan> selectByExample(PenjualanExample example) {
        List<Penjualan> list = getSqlMapClientTemplate().queryForList("penjualan.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table penjualan
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    public Penjualan selectByPrimaryKey(Integer pkPenjualan) {
        Penjualan key = new Penjualan();
        key.setPkPenjualan(pkPenjualan);
        Penjualan record = (Penjualan) getSqlMapClientTemplate().queryForObject("penjualan.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table penjualan
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    public int updateByExampleSelective(Penjualan record, PenjualanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("penjualan.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table penjualan
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    public int updateByExample(Penjualan record, PenjualanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("penjualan.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table penjualan
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    public int updateByPrimaryKeySelective(Penjualan record) {
        int rows = getSqlMapClientTemplate().update("penjualan.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table penjualan
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    public int updateByPrimaryKey(Penjualan record) {
        int rows = getSqlMapClientTemplate().update("penjualan.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table penjualan
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    private static class UpdateByExampleParms extends PenjualanExample {
        private Object record;

        public UpdateByExampleParms(Object record, PenjualanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}