package com.tokogame.dao;

import com.tokogame.domain.Penjualan;
import com.tokogame.domain.PenjualanExample;
import java.util.List;

public interface PenjualanDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table penjualan
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    int countByExample(PenjualanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table penjualan
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    int deleteByExample(PenjualanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table penjualan
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    int deleteByPrimaryKey(Integer pkPenjualan);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table penjualan
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    void insert(Penjualan record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table penjualan
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    void insertSelective(Penjualan record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table penjualan
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    List<Penjualan> selectByExample(PenjualanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table penjualan
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    Penjualan selectByPrimaryKey(Integer pkPenjualan);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table penjualan
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    int updateByExampleSelective(Penjualan record, PenjualanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table penjualan
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    int updateByExample(Penjualan record, PenjualanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table penjualan
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    int updateByPrimaryKeySelective(Penjualan record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table penjualan
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    int updateByPrimaryKey(Penjualan record);
}