package com.tokogame.dao;

import com.tokogame.domain.PromoMain;
import com.tokogame.domain.PromoMainExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class PromoMainDAOImpl extends SqlMapClientDaoSupport implements PromoMainDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_main
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public PromoMainDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_main
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public int countByExample(PromoMainExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("promo_main.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_main
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public int deleteByExample(PromoMainExample example) {
        int rows = getSqlMapClientTemplate().delete("promo_main.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_main
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public int deleteByPrimaryKey(Integer pkPromoMain) {
        PromoMain key = new PromoMain();
        key.setPkPromoMain(pkPromoMain);
        int rows = getSqlMapClientTemplate().delete("promo_main.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_main
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public void insert(PromoMain record) {
        getSqlMapClientTemplate().insert("promo_main.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_main
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public void insertSelective(PromoMain record) {
        getSqlMapClientTemplate().insert("promo_main.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_main
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    @SuppressWarnings("unchecked")
    public List<PromoMain> selectByExample(PromoMainExample example) {
        List<PromoMain> list = getSqlMapClientTemplate().queryForList("promo_main.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_main
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public PromoMain selectByPrimaryKey(Integer pkPromoMain) {
        PromoMain key = new PromoMain();
        key.setPkPromoMain(pkPromoMain);
        PromoMain record = (PromoMain) getSqlMapClientTemplate().queryForObject("promo_main.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_main
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public int updateByExampleSelective(PromoMain record, PromoMainExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("promo_main.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_main
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public int updateByExample(PromoMain record, PromoMainExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("promo_main.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_main
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public int updateByPrimaryKeySelective(PromoMain record) {
        int rows = getSqlMapClientTemplate().update("promo_main.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_main
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public int updateByPrimaryKey(PromoMain record) {
        int rows = getSqlMapClientTemplate().update("promo_main.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table promo_main
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    private static class UpdateByExampleParms extends PromoMainExample {
        private Object record;

        public UpdateByExampleParms(Object record, PromoMainExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}