package com.tokogame.dao;

import com.tokogame.domain.PromoDetail;
import com.tokogame.domain.PromoDetailExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class PromoDetailDAOImpl extends SqlMapClientDaoSupport implements PromoDetailDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_detail
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public PromoDetailDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_detail
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public int countByExample(PromoDetailExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("promo_detail.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_detail
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public int deleteByExample(PromoDetailExample example) {
        int rows = getSqlMapClientTemplate().delete("promo_detail.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_detail
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public int deleteByPrimaryKey(Integer pkPromoDetail) {
        PromoDetail key = new PromoDetail();
        key.setPkPromoDetail(pkPromoDetail);
        int rows = getSqlMapClientTemplate().delete("promo_detail.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_detail
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public void insert(PromoDetail record) {
        getSqlMapClientTemplate().insert("promo_detail.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_detail
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public void insertSelective(PromoDetail record) {
        getSqlMapClientTemplate().insert("promo_detail.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_detail
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    @SuppressWarnings("unchecked")
    public List<PromoDetail> selectByExample(PromoDetailExample example) {
        List<PromoDetail> list = getSqlMapClientTemplate().queryForList("promo_detail.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_detail
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public PromoDetail selectByPrimaryKey(Integer pkPromoDetail) {
        PromoDetail key = new PromoDetail();
        key.setPkPromoDetail(pkPromoDetail);
        PromoDetail record = (PromoDetail) getSqlMapClientTemplate().queryForObject("promo_detail.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_detail
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public int updateByExampleSelective(PromoDetail record, PromoDetailExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("promo_detail.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_detail
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public int updateByExample(PromoDetail record, PromoDetailExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("promo_detail.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_detail
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public int updateByPrimaryKeySelective(PromoDetail record) {
        int rows = getSqlMapClientTemplate().update("promo_detail.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_detail
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public int updateByPrimaryKey(PromoDetail record) {
        int rows = getSqlMapClientTemplate().update("promo_detail.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table promo_detail
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    private static class UpdateByExampleParms extends PromoDetailExample {
        private Object record;

        public UpdateByExampleParms(Object record, PromoDetailExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}