package com.tokogame.dao;

import com.tokogame.domain.PromoMain;
import com.tokogame.domain.PromoMainExample;
import java.util.List;

public interface PromoMainDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_main
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    int countByExample(PromoMainExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_main
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    int deleteByExample(PromoMainExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_main
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    int deleteByPrimaryKey(Integer pkPromoMain);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_main
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    void insert(PromoMain record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_main
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    void insertSelective(PromoMain record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_main
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    List<PromoMain> selectByExample(PromoMainExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_main
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    PromoMain selectByPrimaryKey(Integer pkPromoMain);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_main
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    int updateByExampleSelective(PromoMain record, PromoMainExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_main
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    int updateByExample(PromoMain record, PromoMainExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_main
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    int updateByPrimaryKeySelective(PromoMain record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table promo_main
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    int updateByPrimaryKey(PromoMain record);
}