package com.tokogame.dao;

import com.tokogame.domain.Sequence;
import com.tokogame.domain.SequenceExample;
import java.util.List;

public interface SequenceDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sequence
     *
     * @ibatorgenerated Tue Apr 30 23:45:56 ICT 2013
     */
    int countByExample(SequenceExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sequence
     *
     * @ibatorgenerated Tue Apr 30 23:45:56 ICT 2013
     */
    int deleteByExample(SequenceExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sequence
     *
     * @ibatorgenerated Tue Apr 30 23:45:56 ICT 2013
     */
    int deleteByPrimaryKey(Integer sequenceNo);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sequence
     *
     * @ibatorgenerated Tue Apr 30 23:45:56 ICT 2013
     */
    void insert(Sequence record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sequence
     *
     * @ibatorgenerated Tue Apr 30 23:45:56 ICT 2013
     */
    void insertSelective(Sequence record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sequence
     *
     * @ibatorgenerated Tue Apr 30 23:45:56 ICT 2013
     */
    List<Sequence> selectByExample(SequenceExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sequence
     *
     * @ibatorgenerated Tue Apr 30 23:45:56 ICT 2013
     */
    Sequence selectByPrimaryKey(Integer sequenceNo);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sequence
     *
     * @ibatorgenerated Tue Apr 30 23:45:56 ICT 2013
     */
    int updateByExampleSelective(Sequence record, SequenceExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sequence
     *
     * @ibatorgenerated Tue Apr 30 23:45:56 ICT 2013
     */
    int updateByExample(Sequence record, SequenceExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sequence
     *
     * @ibatorgenerated Tue Apr 30 23:45:56 ICT 2013
     */
    int updateByPrimaryKeySelective(Sequence record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sequence
     *
     * @ibatorgenerated Tue Apr 30 23:45:56 ICT 2013
     */
    int updateByPrimaryKey(Sequence record);
}