package com.tokogame.domain;

public class BelanjaDetail {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column belanja_detail.pk_belanja_detail
     *
     * @ibatorgenerated Wed May 01 17:10:12 ICT 2013
     */
    private Integer pkBelanjaDetail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column belanja_detail.fk_belanja
     *
     * @ibatorgenerated Wed May 01 17:10:12 ICT 2013
     */
    private Integer fkBelanja;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column belanja_detail.fk_item
     *
     * @ibatorgenerated Wed May 01 17:10:12 ICT 2013
     */
    private Integer fkItem;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column belanja_detail.qty
     *
     * @ibatorgenerated Wed May 01 17:10:12 ICT 2013
     */
    private Integer qty;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column belanja_detail.pk_belanja_detail
     *
     * @return the value of belanja_detail.pk_belanja_detail
     *
     * @ibatorgenerated Wed May 01 17:10:12 ICT 2013
     */
    public Integer getPkBelanjaDetail() {
        return pkBelanjaDetail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column belanja_detail.pk_belanja_detail
     *
     * @param pkBelanjaDetail the value for belanja_detail.pk_belanja_detail
     *
     * @ibatorgenerated Wed May 01 17:10:12 ICT 2013
     */
    public void setPkBelanjaDetail(Integer pkBelanjaDetail) {
        this.pkBelanjaDetail = pkBelanjaDetail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column belanja_detail.fk_belanja
     *
     * @return the value of belanja_detail.fk_belanja
     *
     * @ibatorgenerated Wed May 01 17:10:12 ICT 2013
     */
    public Integer getFkBelanja() {
        return fkBelanja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column belanja_detail.fk_belanja
     *
     * @param fkBelanja the value for belanja_detail.fk_belanja
     *
     * @ibatorgenerated Wed May 01 17:10:12 ICT 2013
     */
    public void setFkBelanja(Integer fkBelanja) {
        this.fkBelanja = fkBelanja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column belanja_detail.fk_item
     *
     * @return the value of belanja_detail.fk_item
     *
     * @ibatorgenerated Wed May 01 17:10:12 ICT 2013
     */
    public Integer getFkItem() {
        return fkItem;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column belanja_detail.fk_item
     *
     * @param fkItem the value for belanja_detail.fk_item
     *
     * @ibatorgenerated Wed May 01 17:10:12 ICT 2013
     */
    public void setFkItem(Integer fkItem) {
        this.fkItem = fkItem;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column belanja_detail.qty
     *
     * @return the value of belanja_detail.qty
     *
     * @ibatorgenerated Wed May 01 17:10:12 ICT 2013
     */
    public Integer getQty() {
        return qty;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column belanja_detail.qty
     *
     * @param qty the value for belanja_detail.qty
     *
     * @ibatorgenerated Wed May 01 17:10:12 ICT 2013
     */
    public void setQty(Integer qty) {
        this.qty = qty;
    }
}