package com.tokogame.domain;

public class BelanjaDetail {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column belanja_detail.pk_belanja_detail
     *
     * @ibatorgenerated Thu May 09 22:54:14 ICT 2013
     */
    private Integer pkBelanjaDetail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column belanja_detail.fk_belanja
     *
     * @ibatorgenerated Thu May 09 22:54:14 ICT 2013
     */
    private Integer fkBelanja;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column belanja_detail.fk_item
     *
     * @ibatorgenerated Thu May 09 22:54:14 ICT 2013
     */
    private Integer fkItem;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column belanja_detail.belanja_qty
     *
     * @ibatorgenerated Thu May 09 22:54:14 ICT 2013
     */
    private Integer belanjaQty;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column belanja_detail.harga_belanja
     *
     * @ibatorgenerated Thu May 09 22:54:14 ICT 2013
     */
    private Integer hargaBelanja;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column belanja_detail.is_retur
     *
     * @ibatorgenerated Thu May 09 22:54:14 ICT 2013
     */
    private Integer isRetur;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column belanja_detail.pk_belanja_detail
     *
     * @return the value of belanja_detail.pk_belanja_detail
     *
     * @ibatorgenerated Thu May 09 22:54:14 ICT 2013
     */
    public Integer getPkBelanjaDetail() {
        return pkBelanjaDetail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column belanja_detail.pk_belanja_detail
     *
     * @param pkBelanjaDetail the value for belanja_detail.pk_belanja_detail
     *
     * @ibatorgenerated Thu May 09 22:54:14 ICT 2013
     */
    public void setPkBelanjaDetail(Integer pkBelanjaDetail) {
        this.pkBelanjaDetail = pkBelanjaDetail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column belanja_detail.fk_belanja
     *
     * @return the value of belanja_detail.fk_belanja
     *
     * @ibatorgenerated Thu May 09 22:54:14 ICT 2013
     */
    public Integer getFkBelanja() {
        return fkBelanja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column belanja_detail.fk_belanja
     *
     * @param fkBelanja the value for belanja_detail.fk_belanja
     *
     * @ibatorgenerated Thu May 09 22:54:14 ICT 2013
     */
    public void setFkBelanja(Integer fkBelanja) {
        this.fkBelanja = fkBelanja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column belanja_detail.fk_item
     *
     * @return the value of belanja_detail.fk_item
     *
     * @ibatorgenerated Thu May 09 22:54:14 ICT 2013
     */
    public Integer getFkItem() {
        return fkItem;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column belanja_detail.fk_item
     *
     * @param fkItem the value for belanja_detail.fk_item
     *
     * @ibatorgenerated Thu May 09 22:54:14 ICT 2013
     */
    public void setFkItem(Integer fkItem) {
        this.fkItem = fkItem;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column belanja_detail.belanja_qty
     *
     * @return the value of belanja_detail.belanja_qty
     *
     * @ibatorgenerated Thu May 09 22:54:14 ICT 2013
     */
    public Integer getBelanjaQty() {
        return belanjaQty;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column belanja_detail.belanja_qty
     *
     * @param belanjaQty the value for belanja_detail.belanja_qty
     *
     * @ibatorgenerated Thu May 09 22:54:14 ICT 2013
     */
    public void setBelanjaQty(Integer belanjaQty) {
        this.belanjaQty = belanjaQty;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column belanja_detail.harga_belanja
     *
     * @return the value of belanja_detail.harga_belanja
     *
     * @ibatorgenerated Thu May 09 22:54:14 ICT 2013
     */
    public Integer getHargaBelanja() {
        return hargaBelanja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column belanja_detail.harga_belanja
     *
     * @param hargaBelanja the value for belanja_detail.harga_belanja
     *
     * @ibatorgenerated Thu May 09 22:54:14 ICT 2013
     */
    public void setHargaBelanja(Integer hargaBelanja) {
        this.hargaBelanja = hargaBelanja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column belanja_detail.is_retur
     *
     * @return the value of belanja_detail.is_retur
     *
     * @ibatorgenerated Thu May 09 22:54:14 ICT 2013
     */
    public Integer getIsRetur() {
        return isRetur;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column belanja_detail.is_retur
     *
     * @param isRetur the value for belanja_detail.is_retur
     *
     * @ibatorgenerated Thu May 09 22:54:14 ICT 2013
     */
    public void setIsRetur(Integer isRetur) {
        this.isRetur = isRetur;
    }
}