package com.tokogame.domain;

import java.util.Date;

public class Item {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column item.pk_item
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    private Integer pkItem;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column item.fk_koleksi
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    private Integer fkKoleksi;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column item.fk_kategori
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    private Integer fkKategori;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column item.item_name
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    private String itemName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column item.jenis_item
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    private String jenisItem;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column item.file_size
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    private String fileSize;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column item.harga
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    private Integer harga;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column item.updated_date
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    private Date updatedDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column item.rating
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    private Integer rating;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column item.pk_item
     *
     * @return the value of item.pk_item
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public Integer getPkItem() {
        return pkItem;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column item.pk_item
     *
     * @param pkItem the value for item.pk_item
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public void setPkItem(Integer pkItem) {
        this.pkItem = pkItem;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column item.fk_koleksi
     *
     * @return the value of item.fk_koleksi
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public Integer getFkKoleksi() {
        return fkKoleksi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column item.fk_koleksi
     *
     * @param fkKoleksi the value for item.fk_koleksi
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public void setFkKoleksi(Integer fkKoleksi) {
        this.fkKoleksi = fkKoleksi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column item.fk_kategori
     *
     * @return the value of item.fk_kategori
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public Integer getFkKategori() {
        return fkKategori;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column item.fk_kategori
     *
     * @param fkKategori the value for item.fk_kategori
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public void setFkKategori(Integer fkKategori) {
        this.fkKategori = fkKategori;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column item.item_name
     *
     * @return the value of item.item_name
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column item.item_name
     *
     * @param itemName the value for item.item_name
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column item.jenis_item
     *
     * @return the value of item.jenis_item
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public String getJenisItem() {
        return jenisItem;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column item.jenis_item
     *
     * @param jenisItem the value for item.jenis_item
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public void setJenisItem(String jenisItem) {
        this.jenisItem = jenisItem == null ? null : jenisItem.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column item.file_size
     *
     * @return the value of item.file_size
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public String getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column item.file_size
     *
     * @param fileSize the value for item.file_size
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public void setFileSize(String fileSize) {
        this.fileSize = fileSize == null ? null : fileSize.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column item.harga
     *
     * @return the value of item.harga
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public Integer getHarga() {
        return harga;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column item.harga
     *
     * @param harga the value for item.harga
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public void setHarga(Integer harga) {
        this.harga = harga;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column item.updated_date
     *
     * @return the value of item.updated_date
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column item.updated_date
     *
     * @param updatedDate the value for item.updated_date
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column item.rating
     *
     * @return the value of item.rating
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public Integer getRating() {
        return rating;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column item.rating
     *
     * @param rating the value for item.rating
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public void setRating(Integer rating) {
        this.rating = rating;
    }
}