package com.tokogame.domain;

public class Koleksi {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column koleksi.koleksi_id
     *
     * @ibatorgenerated Tue Apr 16 12:50:12 ICT 2013
     */
    private Integer koleksiId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column koleksi.koleksi_name
     *
     * @ibatorgenerated Tue Apr 16 12:50:12 ICT 2013
     */
    private String koleksiName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column koleksi.koleksi_description
     *
     * @ibatorgenerated Tue Apr 16 12:50:12 ICT 2013
     */
    private String koleksiDescription;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column koleksi.koleksi_id
     *
     * @return the value of koleksi.koleksi_id
     *
     * @ibatorgenerated Tue Apr 16 12:50:12 ICT 2013
     */
    public Integer getKoleksiId() {
        return koleksiId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column koleksi.koleksi_id
     *
     * @param koleksiId the value for koleksi.koleksi_id
     *
     * @ibatorgenerated Tue Apr 16 12:50:12 ICT 2013
     */
    public void setKoleksiId(Integer koleksiId) {
        this.koleksiId = koleksiId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column koleksi.koleksi_name
     *
     * @return the value of koleksi.koleksi_name
     *
     * @ibatorgenerated Tue Apr 16 12:50:12 ICT 2013
     */
    public String getKoleksiName() {
        return koleksiName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column koleksi.koleksi_name
     *
     * @param koleksiName the value for koleksi.koleksi_name
     *
     * @ibatorgenerated Tue Apr 16 12:50:12 ICT 2013
     */
    public void setKoleksiName(String koleksiName) {
        this.koleksiName = koleksiName == null ? null : koleksiName.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column koleksi.koleksi_description
     *
     * @return the value of koleksi.koleksi_description
     *
     * @ibatorgenerated Tue Apr 16 12:50:12 ICT 2013
     */
    public String getKoleksiDescription() {
        return koleksiDescription;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column koleksi.koleksi_description
     *
     * @param koleksiDescription the value for koleksi.koleksi_description
     *
     * @ibatorgenerated Tue Apr 16 12:50:12 ICT 2013
     */
    public void setKoleksiDescription(String koleksiDescription) {
        this.koleksiDescription = koleksiDescription == null ? null : koleksiDescription.trim();
    }
}