package com.tokogame.domain;

public class Koleksi {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column koleksi.pk_koleksi
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    private Integer pkKoleksi;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column koleksi.koleksi_name
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    private String koleksiName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column koleksi.koleksi_desc
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    private String koleksiDesc;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column koleksi.pk_koleksi
     *
     * @return the value of koleksi.pk_koleksi
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public Integer getPkKoleksi() {
        return pkKoleksi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column koleksi.pk_koleksi
     *
     * @param pkKoleksi the value for koleksi.pk_koleksi
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public void setPkKoleksi(Integer pkKoleksi) {
        this.pkKoleksi = pkKoleksi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column koleksi.koleksi_name
     *
     * @return the value of koleksi.koleksi_name
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public String getKoleksiName() {
        return koleksiName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column koleksi.koleksi_name
     *
     * @param koleksiName the value for koleksi.koleksi_name
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public void setKoleksiName(String koleksiName) {
        this.koleksiName = koleksiName == null ? null : koleksiName.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column koleksi.koleksi_desc
     *
     * @return the value of koleksi.koleksi_desc
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public String getKoleksiDesc() {
        return koleksiDesc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column koleksi.koleksi_desc
     *
     * @param koleksiDesc the value for koleksi.koleksi_desc
     *
     * @ibatorgenerated Fri Apr 19 07:17:48 ICT 2013
     */
    public void setKoleksiDesc(String koleksiDesc) {
        this.koleksiDesc = koleksiDesc == null ? null : koleksiDesc.trim();
    }
}