package com.tokogame.domain;

import java.util.Date;

public class Opname {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column opname.pk_opname
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    private Integer pkOpname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column opname.tanggal_opname
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    private Date tanggalOpname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column opname.total_selisih
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    private Integer totalSelisih;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column opname.total_biaya
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    private Integer totalBiaya;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column opname.pk_opname
     *
     * @return the value of opname.pk_opname
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    public Integer getPkOpname() {
        return pkOpname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column opname.pk_opname
     *
     * @param pkOpname the value for opname.pk_opname
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    public void setPkOpname(Integer pkOpname) {
        this.pkOpname = pkOpname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column opname.tanggal_opname
     *
     * @return the value of opname.tanggal_opname
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    public Date getTanggalOpname() {
        return tanggalOpname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column opname.tanggal_opname
     *
     * @param tanggalOpname the value for opname.tanggal_opname
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    public void setTanggalOpname(Date tanggalOpname) {
        this.tanggalOpname = tanggalOpname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column opname.total_selisih
     *
     * @return the value of opname.total_selisih
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    public Integer getTotalSelisih() {
        return totalSelisih;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column opname.total_selisih
     *
     * @param totalSelisih the value for opname.total_selisih
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    public void setTotalSelisih(Integer totalSelisih) {
        this.totalSelisih = totalSelisih;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column opname.total_biaya
     *
     * @return the value of opname.total_biaya
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    public Integer getTotalBiaya() {
        return totalBiaya;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column opname.total_biaya
     *
     * @param totalBiaya the value for opname.total_biaya
     *
     * @ibatorgenerated Thu May 16 11:40:28 ICT 2013
     */
    public void setTotalBiaya(Integer totalBiaya) {
        this.totalBiaya = totalBiaya;
    }
}