package com.tokogame.domain;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PembelianDetailExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    public PembelianDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    protected PembelianDetailExample(PembelianDetailExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table pembelian_detail
     *
     * @ibatorgenerated Thu May 16 17:47:54 ICT 2013
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andPkPembelianDetailIsNull() {
            addCriterion("pk_pembelian_detail is null");
            return this;
        }

        public Criteria andPkPembelianDetailIsNotNull() {
            addCriterion("pk_pembelian_detail is not null");
            return this;
        }

        public Criteria andPkPembelianDetailEqualTo(Integer value) {
            addCriterion("pk_pembelian_detail =", value, "pkPembelianDetail");
            return this;
        }

        public Criteria andPkPembelianDetailNotEqualTo(Integer value) {
            addCriterion("pk_pembelian_detail <>", value, "pkPembelianDetail");
            return this;
        }

        public Criteria andPkPembelianDetailGreaterThan(Integer value) {
            addCriterion("pk_pembelian_detail >", value, "pkPembelianDetail");
            return this;
        }

        public Criteria andPkPembelianDetailGreaterThanOrEqualTo(Integer value) {
            addCriterion("pk_pembelian_detail >=", value, "pkPembelianDetail");
            return this;
        }

        public Criteria andPkPembelianDetailLessThan(Integer value) {
            addCriterion("pk_pembelian_detail <", value, "pkPembelianDetail");
            return this;
        }

        public Criteria andPkPembelianDetailLessThanOrEqualTo(Integer value) {
            addCriterion("pk_pembelian_detail <=", value, "pkPembelianDetail");
            return this;
        }

        public Criteria andPkPembelianDetailIn(List<Integer> values) {
            addCriterion("pk_pembelian_detail in", values, "pkPembelianDetail");
            return this;
        }

        public Criteria andPkPembelianDetailNotIn(List<Integer> values) {
            addCriterion("pk_pembelian_detail not in", values, "pkPembelianDetail");
            return this;
        }

        public Criteria andPkPembelianDetailBetween(Integer value1, Integer value2) {
            addCriterion("pk_pembelian_detail between", value1, value2, "pkPembelianDetail");
            return this;
        }

        public Criteria andPkPembelianDetailNotBetween(Integer value1, Integer value2) {
            addCriterion("pk_pembelian_detail not between", value1, value2, "pkPembelianDetail");
            return this;
        }

        public Criteria andFkPembelianIsNull() {
            addCriterion("fk_pembelian is null");
            return this;
        }

        public Criteria andFkPembelianIsNotNull() {
            addCriterion("fk_pembelian is not null");
            return this;
        }

        public Criteria andFkPembelianEqualTo(Integer value) {
            addCriterion("fk_pembelian =", value, "fkPembelian");
            return this;
        }

        public Criteria andFkPembelianNotEqualTo(Integer value) {
            addCriterion("fk_pembelian <>", value, "fkPembelian");
            return this;
        }

        public Criteria andFkPembelianGreaterThan(Integer value) {
            addCriterion("fk_pembelian >", value, "fkPembelian");
            return this;
        }

        public Criteria andFkPembelianGreaterThanOrEqualTo(Integer value) {
            addCriterion("fk_pembelian >=", value, "fkPembelian");
            return this;
        }

        public Criteria andFkPembelianLessThan(Integer value) {
            addCriterion("fk_pembelian <", value, "fkPembelian");
            return this;
        }

        public Criteria andFkPembelianLessThanOrEqualTo(Integer value) {
            addCriterion("fk_pembelian <=", value, "fkPembelian");
            return this;
        }

        public Criteria andFkPembelianIn(List<Integer> values) {
            addCriterion("fk_pembelian in", values, "fkPembelian");
            return this;
        }

        public Criteria andFkPembelianNotIn(List<Integer> values) {
            addCriterion("fk_pembelian not in", values, "fkPembelian");
            return this;
        }

        public Criteria andFkPembelianBetween(Integer value1, Integer value2) {
            addCriterion("fk_pembelian between", value1, value2, "fkPembelian");
            return this;
        }

        public Criteria andFkPembelianNotBetween(Integer value1, Integer value2) {
            addCriterion("fk_pembelian not between", value1, value2, "fkPembelian");
            return this;
        }

        public Criteria andFkItemIsNull() {
            addCriterion("fk_item is null");
            return this;
        }

        public Criteria andFkItemIsNotNull() {
            addCriterion("fk_item is not null");
            return this;
        }

        public Criteria andFkItemEqualTo(Integer value) {
            addCriterion("fk_item =", value, "fkItem");
            return this;
        }

        public Criteria andFkItemNotEqualTo(Integer value) {
            addCriterion("fk_item <>", value, "fkItem");
            return this;
        }

        public Criteria andFkItemGreaterThan(Integer value) {
            addCriterion("fk_item >", value, "fkItem");
            return this;
        }

        public Criteria andFkItemGreaterThanOrEqualTo(Integer value) {
            addCriterion("fk_item >=", value, "fkItem");
            return this;
        }

        public Criteria andFkItemLessThan(Integer value) {
            addCriterion("fk_item <", value, "fkItem");
            return this;
        }

        public Criteria andFkItemLessThanOrEqualTo(Integer value) {
            addCriterion("fk_item <=", value, "fkItem");
            return this;
        }

        public Criteria andFkItemIn(List<Integer> values) {
            addCriterion("fk_item in", values, "fkItem");
            return this;
        }

        public Criteria andFkItemNotIn(List<Integer> values) {
            addCriterion("fk_item not in", values, "fkItem");
            return this;
        }

        public Criteria andFkItemBetween(Integer value1, Integer value2) {
            addCriterion("fk_item between", value1, value2, "fkItem");
            return this;
        }

        public Criteria andFkItemNotBetween(Integer value1, Integer value2) {
            addCriterion("fk_item not between", value1, value2, "fkItem");
            return this;
        }

        public Criteria andHargaPembelianIsNull() {
            addCriterion("harga_pembelian is null");
            return this;
        }

        public Criteria andHargaPembelianIsNotNull() {
            addCriterion("harga_pembelian is not null");
            return this;
        }

        public Criteria andHargaPembelianEqualTo(Integer value) {
            addCriterion("harga_pembelian =", value, "hargaPembelian");
            return this;
        }

        public Criteria andHargaPembelianNotEqualTo(Integer value) {
            addCriterion("harga_pembelian <>", value, "hargaPembelian");
            return this;
        }

        public Criteria andHargaPembelianGreaterThan(Integer value) {
            addCriterion("harga_pembelian >", value, "hargaPembelian");
            return this;
        }

        public Criteria andHargaPembelianGreaterThanOrEqualTo(Integer value) {
            addCriterion("harga_pembelian >=", value, "hargaPembelian");
            return this;
        }

        public Criteria andHargaPembelianLessThan(Integer value) {
            addCriterion("harga_pembelian <", value, "hargaPembelian");
            return this;
        }

        public Criteria andHargaPembelianLessThanOrEqualTo(Integer value) {
            addCriterion("harga_pembelian <=", value, "hargaPembelian");
            return this;
        }

        public Criteria andHargaPembelianIn(List<Integer> values) {
            addCriterion("harga_pembelian in", values, "hargaPembelian");
            return this;
        }

        public Criteria andHargaPembelianNotIn(List<Integer> values) {
            addCriterion("harga_pembelian not in", values, "hargaPembelian");
            return this;
        }

        public Criteria andHargaPembelianBetween(Integer value1, Integer value2) {
            addCriterion("harga_pembelian between", value1, value2, "hargaPembelian");
            return this;
        }

        public Criteria andHargaPembelianNotBetween(Integer value1, Integer value2) {
            addCriterion("harga_pembelian not between", value1, value2, "hargaPembelian");
            return this;
        }

        public Criteria andPembelianQtyIsNull() {
            addCriterion("pembelian_qty is null");
            return this;
        }

        public Criteria andPembelianQtyIsNotNull() {
            addCriterion("pembelian_qty is not null");
            return this;
        }

        public Criteria andPembelianQtyEqualTo(Integer value) {
            addCriterion("pembelian_qty =", value, "pembelianQty");
            return this;
        }

        public Criteria andPembelianQtyNotEqualTo(Integer value) {
            addCriterion("pembelian_qty <>", value, "pembelianQty");
            return this;
        }

        public Criteria andPembelianQtyGreaterThan(Integer value) {
            addCriterion("pembelian_qty >", value, "pembelianQty");
            return this;
        }

        public Criteria andPembelianQtyGreaterThanOrEqualTo(Integer value) {
            addCriterion("pembelian_qty >=", value, "pembelianQty");
            return this;
        }

        public Criteria andPembelianQtyLessThan(Integer value) {
            addCriterion("pembelian_qty <", value, "pembelianQty");
            return this;
        }

        public Criteria andPembelianQtyLessThanOrEqualTo(Integer value) {
            addCriterion("pembelian_qty <=", value, "pembelianQty");
            return this;
        }

        public Criteria andPembelianQtyIn(List<Integer> values) {
            addCriterion("pembelian_qty in", values, "pembelianQty");
            return this;
        }

        public Criteria andPembelianQtyNotIn(List<Integer> values) {
            addCriterion("pembelian_qty not in", values, "pembelianQty");
            return this;
        }

        public Criteria andPembelianQtyBetween(Integer value1, Integer value2) {
            addCriterion("pembelian_qty between", value1, value2, "pembelianQty");
            return this;
        }

        public Criteria andPembelianQtyNotBetween(Integer value1, Integer value2) {
            addCriterion("pembelian_qty not between", value1, value2, "pembelianQty");
            return this;
        }

        public Criteria andKeteranganIsNull() {
            addCriterion("keterangan is null");
            return this;
        }

        public Criteria andKeteranganIsNotNull() {
            addCriterion("keterangan is not null");
            return this;
        }

        public Criteria andKeteranganEqualTo(String value) {
            addCriterion("keterangan =", value, "keterangan");
            return this;
        }

        public Criteria andKeteranganNotEqualTo(String value) {
            addCriterion("keterangan <>", value, "keterangan");
            return this;
        }

        public Criteria andKeteranganGreaterThan(String value) {
            addCriterion("keterangan >", value, "keterangan");
            return this;
        }

        public Criteria andKeteranganGreaterThanOrEqualTo(String value) {
            addCriterion("keterangan >=", value, "keterangan");
            return this;
        }

        public Criteria andKeteranganLessThan(String value) {
            addCriterion("keterangan <", value, "keterangan");
            return this;
        }

        public Criteria andKeteranganLessThanOrEqualTo(String value) {
            addCriterion("keterangan <=", value, "keterangan");
            return this;
        }

        public Criteria andKeteranganLike(String value) {
            addCriterion("keterangan like", value, "keterangan");
            return this;
        }

        public Criteria andKeteranganNotLike(String value) {
            addCriterion("keterangan not like", value, "keterangan");
            return this;
        }

        public Criteria andKeteranganIn(List<String> values) {
            addCriterion("keterangan in", values, "keterangan");
            return this;
        }

        public Criteria andKeteranganNotIn(List<String> values) {
            addCriterion("keterangan not in", values, "keterangan");
            return this;
        }

        public Criteria andKeteranganBetween(String value1, String value2) {
            addCriterion("keterangan between", value1, value2, "keterangan");
            return this;
        }

        public Criteria andKeteranganNotBetween(String value1, String value2) {
            addCriterion("keterangan not between", value1, value2, "keterangan");
            return this;
        }
    }
}