package com.tokogame.domain;

import java.util.Date;

public class Penjualan {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column penjualan.pk_penjualan
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    private Integer pkPenjualan;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column penjualan.fk_belanja
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    private Integer fkBelanja;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column penjualan.jual_qty
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    private Integer jualQty;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column penjualan.total_beli
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    private Integer totalBeli;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column penjualan.total_retur
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    private Integer totalRetur;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column penjualan.total_belanja
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    private Integer totalBelanja;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column penjualan.total_bayar
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    private Integer totalBayar;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column penjualan.total_kembali
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    private Integer totalKembali;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column penjualan.tanggal_jual
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    private Date tanggalJual;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column penjualan.pk_penjualan
     *
     * @return the value of penjualan.pk_penjualan
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    public Integer getPkPenjualan() {
        return pkPenjualan;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column penjualan.pk_penjualan
     *
     * @param pkPenjualan the value for penjualan.pk_penjualan
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    public void setPkPenjualan(Integer pkPenjualan) {
        this.pkPenjualan = pkPenjualan;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column penjualan.fk_belanja
     *
     * @return the value of penjualan.fk_belanja
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    public Integer getFkBelanja() {
        return fkBelanja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column penjualan.fk_belanja
     *
     * @param fkBelanja the value for penjualan.fk_belanja
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    public void setFkBelanja(Integer fkBelanja) {
        this.fkBelanja = fkBelanja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column penjualan.jual_qty
     *
     * @return the value of penjualan.jual_qty
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    public Integer getJualQty() {
        return jualQty;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column penjualan.jual_qty
     *
     * @param jualQty the value for penjualan.jual_qty
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    public void setJualQty(Integer jualQty) {
        this.jualQty = jualQty;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column penjualan.total_beli
     *
     * @return the value of penjualan.total_beli
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    public Integer getTotalBeli() {
        return totalBeli;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column penjualan.total_beli
     *
     * @param totalBeli the value for penjualan.total_beli
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    public void setTotalBeli(Integer totalBeli) {
        this.totalBeli = totalBeli;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column penjualan.total_retur
     *
     * @return the value of penjualan.total_retur
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    public Integer getTotalRetur() {
        return totalRetur;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column penjualan.total_retur
     *
     * @param totalRetur the value for penjualan.total_retur
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    public void setTotalRetur(Integer totalRetur) {
        this.totalRetur = totalRetur;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column penjualan.total_belanja
     *
     * @return the value of penjualan.total_belanja
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    public Integer getTotalBelanja() {
        return totalBelanja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column penjualan.total_belanja
     *
     * @param totalBelanja the value for penjualan.total_belanja
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    public void setTotalBelanja(Integer totalBelanja) {
        this.totalBelanja = totalBelanja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column penjualan.total_bayar
     *
     * @return the value of penjualan.total_bayar
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    public Integer getTotalBayar() {
        return totalBayar;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column penjualan.total_bayar
     *
     * @param totalBayar the value for penjualan.total_bayar
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    public void setTotalBayar(Integer totalBayar) {
        this.totalBayar = totalBayar;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column penjualan.total_kembali
     *
     * @return the value of penjualan.total_kembali
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    public Integer getTotalKembali() {
        return totalKembali;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column penjualan.total_kembali
     *
     * @param totalKembali the value for penjualan.total_kembali
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    public void setTotalKembali(Integer totalKembali) {
        this.totalKembali = totalKembali;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column penjualan.tanggal_jual
     *
     * @return the value of penjualan.tanggal_jual
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    public Date getTanggalJual() {
        return tanggalJual;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column penjualan.tanggal_jual
     *
     * @param tanggalJual the value for penjualan.tanggal_jual
     *
     * @ibatorgenerated Fri May 10 01:12:44 ICT 2013
     */
    public void setTanggalJual(Date tanggalJual) {
        this.tanggalJual = tanggalJual;
    }
}