package com.tokogame.domain;

import java.util.Date;

public class PromoMain {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column promo_main.pk_promo_main
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    private Integer pkPromoMain;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column promo_main.promo_name
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    private String promoName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column promo_main.promo_desc
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    private String promoDesc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column promo_main.promo_active
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    private Integer promoActive;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column promo_main.promo_active_date
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    private Date promoActiveDate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column promo_main.pk_promo_main
     *
     * @return the value of promo_main.pk_promo_main
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public Integer getPkPromoMain() {
        return pkPromoMain;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column promo_main.pk_promo_main
     *
     * @param pkPromoMain the value for promo_main.pk_promo_main
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public void setPkPromoMain(Integer pkPromoMain) {
        this.pkPromoMain = pkPromoMain;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column promo_main.promo_name
     *
     * @return the value of promo_main.promo_name
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public String getPromoName() {
        return promoName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column promo_main.promo_name
     *
     * @param promoName the value for promo_main.promo_name
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public void setPromoName(String promoName) {
        this.promoName = promoName == null ? null : promoName.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column promo_main.promo_desc
     *
     * @return the value of promo_main.promo_desc
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public String getPromoDesc() {
        return promoDesc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column promo_main.promo_desc
     *
     * @param promoDesc the value for promo_main.promo_desc
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public void setPromoDesc(String promoDesc) {
        this.promoDesc = promoDesc == null ? null : promoDesc.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column promo_main.promo_active
     *
     * @return the value of promo_main.promo_active
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public Integer getPromoActive() {
        return promoActive;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column promo_main.promo_active
     *
     * @param promoActive the value for promo_main.promo_active
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public void setPromoActive(Integer promoActive) {
        this.promoActive = promoActive;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column promo_main.promo_active_date
     *
     * @return the value of promo_main.promo_active_date
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public Date getPromoActiveDate() {
        return promoActiveDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column promo_main.promo_active_date
     *
     * @param promoActiveDate the value for promo_main.promo_active_date
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public void setPromoActiveDate(Date promoActiveDate) {
        this.promoActiveDate = promoActiveDate;
    }
}