package com.tokogame.domain;

public class PromoDetail {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column promo_detail.pk_promo_detail
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    private Integer pkPromoDetail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column promo_detail.fk_promo_main
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    private Integer fkPromoMain;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column promo_detail.fk_item
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    private Integer fkItem;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column promo_detail.nilai_diskon
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    private Integer nilaiDiskon;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column promo_detail.jenis_diskon
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    private String jenisDiskon;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column promo_detail.pk_promo_detail
     *
     * @return the value of promo_detail.pk_promo_detail
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public Integer getPkPromoDetail() {
        return pkPromoDetail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column promo_detail.pk_promo_detail
     *
     * @param pkPromoDetail the value for promo_detail.pk_promo_detail
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public void setPkPromoDetail(Integer pkPromoDetail) {
        this.pkPromoDetail = pkPromoDetail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column promo_detail.fk_promo_main
     *
     * @return the value of promo_detail.fk_promo_main
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public Integer getFkPromoMain() {
        return fkPromoMain;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column promo_detail.fk_promo_main
     *
     * @param fkPromoMain the value for promo_detail.fk_promo_main
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public void setFkPromoMain(Integer fkPromoMain) {
        this.fkPromoMain = fkPromoMain;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column promo_detail.fk_item
     *
     * @return the value of promo_detail.fk_item
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public Integer getFkItem() {
        return fkItem;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column promo_detail.fk_item
     *
     * @param fkItem the value for promo_detail.fk_item
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public void setFkItem(Integer fkItem) {
        this.fkItem = fkItem;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column promo_detail.nilai_diskon
     *
     * @return the value of promo_detail.nilai_diskon
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public Integer getNilaiDiskon() {
        return nilaiDiskon;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column promo_detail.nilai_diskon
     *
     * @param nilaiDiskon the value for promo_detail.nilai_diskon
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public void setNilaiDiskon(Integer nilaiDiskon) {
        this.nilaiDiskon = nilaiDiskon;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column promo_detail.jenis_diskon
     *
     * @return the value of promo_detail.jenis_diskon
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public String getJenisDiskon() {
        return jenisDiskon;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column promo_detail.jenis_diskon
     *
     * @param jenisDiskon the value for promo_detail.jenis_diskon
     *
     * @ibatorgenerated Sun May 12 15:46:16 ICT 2013
     */
    public void setJenisDiskon(String jenisDiskon) {
        this.jenisDiskon = jenisDiskon == null ? null : jenisDiskon.trim();
    }
}