package com.tokogame.domain;

public class Retur {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column retur.pk_retur
     *
     * @ibatorgenerated Thu May 09 00:35:39 ICT 2013
     */
    private Integer pkRetur;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column retur.fk_belanja_detail
     *
     * @ibatorgenerated Thu May 09 00:35:39 ICT 2013
     */
    private Integer fkBelanjaDetail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column retur.fk_belanja
     *
     * @ibatorgenerated Thu May 09 00:35:39 ICT 2013
     */
    private Integer fkBelanja;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column retur.fk_item
     *
     * @ibatorgenerated Thu May 09 00:35:39 ICT 2013
     */
    private Integer fkItem;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column retur.retur_qty
     *
     * @ibatorgenerated Thu May 09 00:35:39 ICT 2013
     */
    private Integer returQty;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column retur.reason
     *
     * @ibatorgenerated Thu May 09 00:35:39 ICT 2013
     */
    private String reason;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column retur.pk_retur
     *
     * @return the value of retur.pk_retur
     *
     * @ibatorgenerated Thu May 09 00:35:39 ICT 2013
     */
    public Integer getPkRetur() {
        return pkRetur;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column retur.pk_retur
     *
     * @param pkRetur the value for retur.pk_retur
     *
     * @ibatorgenerated Thu May 09 00:35:39 ICT 2013
     */
    public void setPkRetur(Integer pkRetur) {
        this.pkRetur = pkRetur;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column retur.fk_belanja_detail
     *
     * @return the value of retur.fk_belanja_detail
     *
     * @ibatorgenerated Thu May 09 00:35:39 ICT 2013
     */
    public Integer getFkBelanjaDetail() {
        return fkBelanjaDetail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column retur.fk_belanja_detail
     *
     * @param fkBelanjaDetail the value for retur.fk_belanja_detail
     *
     * @ibatorgenerated Thu May 09 00:35:39 ICT 2013
     */
    public void setFkBelanjaDetail(Integer fkBelanjaDetail) {
        this.fkBelanjaDetail = fkBelanjaDetail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column retur.fk_belanja
     *
     * @return the value of retur.fk_belanja
     *
     * @ibatorgenerated Thu May 09 00:35:39 ICT 2013
     */
    public Integer getFkBelanja() {
        return fkBelanja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column retur.fk_belanja
     *
     * @param fkBelanja the value for retur.fk_belanja
     *
     * @ibatorgenerated Thu May 09 00:35:39 ICT 2013
     */
    public void setFkBelanja(Integer fkBelanja) {
        this.fkBelanja = fkBelanja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column retur.fk_item
     *
     * @return the value of retur.fk_item
     *
     * @ibatorgenerated Thu May 09 00:35:39 ICT 2013
     */
    public Integer getFkItem() {
        return fkItem;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column retur.fk_item
     *
     * @param fkItem the value for retur.fk_item
     *
     * @ibatorgenerated Thu May 09 00:35:39 ICT 2013
     */
    public void setFkItem(Integer fkItem) {
        this.fkItem = fkItem;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column retur.retur_qty
     *
     * @return the value of retur.retur_qty
     *
     * @ibatorgenerated Thu May 09 00:35:39 ICT 2013
     */
    public Integer getReturQty() {
        return returQty;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column retur.retur_qty
     *
     * @param returQty the value for retur.retur_qty
     *
     * @ibatorgenerated Thu May 09 00:35:39 ICT 2013
     */
    public void setReturQty(Integer returQty) {
        this.returQty = returQty;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column retur.reason
     *
     * @return the value of retur.reason
     *
     * @ibatorgenerated Thu May 09 00:35:39 ICT 2013
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column retur.reason
     *
     * @param reason the value for retur.reason
     *
     * @ibatorgenerated Thu May 09 00:35:39 ICT 2013
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }
}