package com.tokogame.domain;

public class User {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.pk_user
     *
     * @ibatorgenerated Mon May 06 15:26:57 ICT 2013
     */
    private Integer pkUser;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.user_login
     *
     * @ibatorgenerated Mon May 06 15:26:57 ICT 2013
     */
    private String userLogin;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.name
     *
     * @ibatorgenerated Mon May 06 15:26:57 ICT 2013
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.handphone
     *
     * @ibatorgenerated Mon May 06 15:26:57 ICT 2013
     */
    private String handphone;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.address
     *
     * @ibatorgenerated Mon May 06 15:26:57 ICT 2013
     */
    private String address;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.password
     *
     * @ibatorgenerated Mon May 06 15:26:57 ICT 2013
     */
    private String password;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.role
     *
     * @ibatorgenerated Mon May 06 15:26:57 ICT 2013
     */
    private String role;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.active
     *
     * @ibatorgenerated Mon May 06 15:26:57 ICT 2013
     */
    private Integer active;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.pk_user
     *
     * @return the value of user.pk_user
     *
     * @ibatorgenerated Mon May 06 15:26:57 ICT 2013
     */
    public Integer getPkUser() {
        return pkUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.pk_user
     *
     * @param pkUser the value for user.pk_user
     *
     * @ibatorgenerated Mon May 06 15:26:57 ICT 2013
     */
    public void setPkUser(Integer pkUser) {
        this.pkUser = pkUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.user_login
     *
     * @return the value of user.user_login
     *
     * @ibatorgenerated Mon May 06 15:26:57 ICT 2013
     */
    public String getUserLogin() {
        return userLogin;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.user_login
     *
     * @param userLogin the value for user.user_login
     *
     * @ibatorgenerated Mon May 06 15:26:57 ICT 2013
     */
    public void setUserLogin(String userLogin) {
        this.userLogin = userLogin == null ? null : userLogin.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @ibatorgenerated Mon May 06 15:26:57 ICT 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @ibatorgenerated Mon May 06 15:26:57 ICT 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.handphone
     *
     * @return the value of user.handphone
     *
     * @ibatorgenerated Mon May 06 15:26:57 ICT 2013
     */
    public String getHandphone() {
        return handphone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.handphone
     *
     * @param handphone the value for user.handphone
     *
     * @ibatorgenerated Mon May 06 15:26:57 ICT 2013
     */
    public void setHandphone(String handphone) {
        this.handphone = handphone == null ? null : handphone.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.address
     *
     * @return the value of user.address
     *
     * @ibatorgenerated Mon May 06 15:26:57 ICT 2013
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.address
     *
     * @param address the value for user.address
     *
     * @ibatorgenerated Mon May 06 15:26:57 ICT 2013
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @ibatorgenerated Mon May 06 15:26:57 ICT 2013
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @ibatorgenerated Mon May 06 15:26:57 ICT 2013
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.role
     *
     * @return the value of user.role
     *
     * @ibatorgenerated Mon May 06 15:26:57 ICT 2013
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.role
     *
     * @param role the value for user.role
     *
     * @ibatorgenerated Mon May 06 15:26:57 ICT 2013
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.active
     *
     * @return the value of user.active
     *
     * @ibatorgenerated Mon May 06 15:26:57 ICT 2013
     */
    public Integer getActive() {
        return active;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.active
     *
     * @param active the value for user.active
     *
     * @ibatorgenerated Mon May 06 15:26:57 ICT 2013
     */
    public void setActive(Integer active) {
        this.active = active;
    }
}