package com.tokogame.domain;

public class User {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.user_id
     *
     * @ibatorgenerated Sun Apr 21 11:45:59 ICT 2013
     */
    private Integer userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.user_login
     *
     * @ibatorgenerated Sun Apr 21 11:45:59 ICT 2013
     */
    private String userLogin;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.password
     *
     * @ibatorgenerated Sun Apr 21 11:45:59 ICT 2013
     */
    private String password;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.role
     *
     * @ibatorgenerated Sun Apr 21 11:45:59 ICT 2013
     */
    private String role;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.active
     *
     * @ibatorgenerated Sun Apr 21 11:45:59 ICT 2013
     */
    private Integer active;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @ibatorgenerated Sun Apr 21 11:45:59 ICT 2013
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @ibatorgenerated Sun Apr 21 11:45:59 ICT 2013
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.user_login
     *
     * @return the value of user.user_login
     *
     * @ibatorgenerated Sun Apr 21 11:45:59 ICT 2013
     */
    public String getUserLogin() {
        return userLogin;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.user_login
     *
     * @param userLogin the value for user.user_login
     *
     * @ibatorgenerated Sun Apr 21 11:45:59 ICT 2013
     */
    public void setUserLogin(String userLogin) {
        this.userLogin = userLogin == null ? null : userLogin.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @ibatorgenerated Sun Apr 21 11:45:59 ICT 2013
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @ibatorgenerated Sun Apr 21 11:45:59 ICT 2013
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.role
     *
     * @return the value of user.role
     *
     * @ibatorgenerated Sun Apr 21 11:45:59 ICT 2013
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.role
     *
     * @param role the value for user.role
     *
     * @ibatorgenerated Sun Apr 21 11:45:59 ICT 2013
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.active
     *
     * @return the value of user.active
     *
     * @ibatorgenerated Sun Apr 21 11:45:59 ICT 2013
     */
    public Integer getActive() {
        return active;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.active
     *
     * @param active the value for user.active
     *
     * @ibatorgenerated Sun Apr 21 11:45:59 ICT 2013
     */
    public void setActive(Integer active) {
        this.active = active;
    }
}